app/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='users/index.html'), name='main-page'),
    path('products/', include('products.urls')),
    path('ads/', include('advertisements.urls')),
    path('contracts/', include('contracts.urls')),
    path('accounts/', include('registration.urls')),
    path('leads/', include('leads.urls')),
    path('customers/', include('customers.urls')),
]


if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

app/contracts/models.py
from django.db import models

from products.models import Product


class Contract(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    products = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукты')
    document_file = models.FileField(null=True, upload_to='contract/documents/', verbose_name='Документ файл')
    start_date = models.DateTimeField(verbose_name='Начальная дата')
    end_date = models.DateTimeField(verbose_name='Конечная дата')
    cost = models.IntegerField(default=0, verbose_name='Цена')

    def __str__(self):
        return f'Контракт№{self.id}: {self.name}'

app/customers/models.py
from django.db import models

from contracts.models import Contract
from leads.models import Lead


class Customer(models.Model):
    lead = models.ForeignKey(Lead, on_delete=models.CASCADE, verbose_name='Потенциальный клиент')
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE, verbose_name='Контракт')

    def __str__(self):
        return f'Потенциальный клиент№{self.id}: {self.lead.last_name} {self.lead.first_name}'

app/leads/models.py
from django.db import models

from advertisements.models import Advertisements


class Lead(models.Model):
    first_name = models.CharField(max_length=100, verbose_name='Имя')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия')
    phone = models.CharField(max_length=12, verbose_name='Номер телефона')
    email = models.CharField(max_length=100)
    ads_company = models.ForeignKey(Advertisements, on_delete=models.CASCADE, verbose_name='Рекламная кампания, из которой он '
                                                                               'узнал об услуге.')

    def __str__(self):
        return f'Lead№{self.id}: {self.last_name} {self.first_name}'

app/products/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.CharField(max_length=100, verbose_name='Описание')
    cost = models.CharField(max_length=100, default=0, verbose_name='Цена')

    def __str__(self):
        return self.name

app/templates/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>CRM</title>
</head>
<body>

<div class="main-container d-flex">
    <div class="sidebar" id="side_nav">
        <div class="header-box px-3 pt-4 pb-4">
            <h1 class="fs-4 nav-logo">
                <span class="text-black text-uppercase font-weight-bold">
                    <a class="link-dark text-decoration-none" href="/">CRM BACKOFFICE</a>
                </span>
            </h1>
        </div>
        <ul class="list-unstyled px-2">
            {% if perms.products.view_product %}
            <li><a href="/products/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-microchip"></i></span><span class="ml-1"> Услуги</span>
            </a></li>
            {% endif %}
            {% if perms.advertisements.view_advertisements %}
            <li><a href="/ads/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-ad"></i></span><span class="ml-1"> Рекламные компании</span>
            </a></li>
            {% endif %}
            {% if perms.leads.view_lead %}
            <li><a href="/leads/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-user-clock"></i></span><span class="px-1"> Лиды</span>
            </a></li>
            {% endif %}
            {% if perms.contracts.view_contract %}
            <li><a href="/contracts/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-file-alt"></i></span><span class="px-1"> Контракты</span>
            </a></li>
            {% endif %}
            {% if perms.customers.view_customer %}
            <li><a href="/customers/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-user-check"></i></span><span class="px-1"> Активные клиенты</span>
            </a></li>
            {% endif %}
            <li>
                <hr>
            </li>
            <li><a href="/accounts/logout" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-sign-out-alt"></i></span><span class="px-1"> Выход</span>
            </a></li>
        </ul>
    </div>
    <div class="content px-3 pt-4">
        {% block content %}{% endblock %}
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>